import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    English: {
        home: "Home",
        skillHub: "Skill Hub",
        health: "Health",
        tagline: "Empowering Rural Women Through Technology",
        periodBot: "Period Care Bot",
        pregnancyBot: "Pregnancy Care Bot",
        askSomething: "Ask something...",
        startChat: "Start Chat",
        listen: "Listen",
        speak: "Speak",
        sakhiTyping: "Sakhi is typing...",
        periodTrackerSetup: "Period Tracker Setup",
        yourAge: "Your Age",
        lastPeriodDate: "Last Period Date",
        registerAsCreator: "Register as Creator",
        villageMarket: "Village Market",
        buy: "Buy",
        price: "Price",
        name: "Name",
        village: "Village",
        skills: "Skills",
        experience: "Experience",
        contact: "Contact",
        submit: "Submit",
        close: "Close",
        login: "Login",
        signup: "Sign Up",
        phoneNumber: "Phone Number",
        password: "Password",
        noAccount: "Don't have an account?",
        haveAccount: "Already have an account?",
        welcomeBack: "Welcome Back",
        createAccount: "Create Account",
        profile: "Profile",
        myOrders: "My Orders",
        paymentHistory: "Payment History",
        chatWithCreator: "Chat with Sakhi (Creator)",
        status: "Status",
        completed: "Completed",
        pending: "Pending",
        amount: "Amount",
        date: "Date",
        messagePlaceholder: "Type your message to the creator...",
        chooseAssistant: "Choose Your Assistant",
        assistantDesc: "Our AI-powered assistants are here to guide you with privacy and care. (Not a replacement for a doctor).",
        pregnancyJourney: "Pregnancy Journey",
        pregnancyStartDate: "Pregnancy Start Date (Approx)",
        safety: "Safety",
        shelterMap: "Safety Map",
        sos: "SOS",
        schemes: "Govt Schemes",
        education: "Learning",
        community: "Community",
        emergencyContact: "Emergency Contact",
        triggerSOS: "Trigger SOS Alert",
        learningHub: "Skill Learning Hub",
        eligibleSchemes: "Schemes for You",
        myShop: "My Shop",
        addProduct: "Add New Product",
        editProduct: "Edit Product",
        delete: "Delete",
        saveChanges: "Save Changes",
    },
    Hindi: {
        home: "होम",
        skillHub: "कौशल केंद्र",
        health: "स्वास्थ्य",
        tagline: "तकनीक के माध्यम से ग्रामीण महिलाओं का सशक्तिकरण",
        periodBot: "मासिक धर्म देखभाल बॉट",
        pregnancyBot: "गर्भावस्था देखभाल बॉट",
        askSomething: "कुछ पूछें...",
        startChat: "चैट शुरू करें",
        listen: "सुनें",
        speak: "बोलें",
        sakhiTyping: "सखी लिख रही है...",
        periodTrackerSetup: "पीरियड ट्रैकर सेटअप",
        yourAge: "आपकी उम्र",
        lastPeriodDate: "पिछली अवधि की तारीख",
        registerAsCreator: "क्रिएटर के रूप में पंजीकरण करें",
        villageMarket: "गांव का बाजार",
        buy: "खरीदें",
        price: "कीमत",
        name: "नाम",
        village: "गांव",
        skills: "कौशल",
        experience: "अनुभव",
        contact: "संपर्क",
        submit: "जमा करें",
        close: "बंद करें",
        login: "लॉगिन",
        signup: "साइन अप करें",
        phoneNumber: "फोन नंबर",
        password: "पासवर्ड",
        noAccount: "क्या आपके पास खाता नहीं है?",
        haveAccount: "पहले से ही एक खाता है?",
        welcomeBack: "आपका स्वागत है",
        createAccount: "खाता बनाएँ",
        profile: "प्रोफ़ाइल",
        myOrders: "मेरे आदेश",
        paymentHistory: "भुगतान इतिहास",
        chatWithCreator: "सखी (क्रिएटर) के साथ बातचीत",
        status: "स्थिति",
        completed: "पूरा हुआ",
        pending: "लंबित",
        amount: "रकम",
        date: "तारीख",
        messagePlaceholder: "क्रिएटर को संदेश लिखें...",
        chooseAssistant: "अपना सहायक चुनें",
        assistantDesc: "हमारे एआई-संचालित सहायक गोपनीयता और देखभाल के साथ आपका मार्गदर्शन करने के लिए यहां हैं। (डॉक्टर का विकल्प नहीं)।",
        pregnancyJourney: "गर्भावस्था की यात्रा",
        pregnancyStartDate: "गर्भावस्था शुरू होने की तारीख (लगभग)",
        safety: "सुरक्षा",
        shelterMap: "सुरक्षा मानचित्र",
        sos: "संकट बटन (SOS)",
        schemes: "सरकारी योजनाएं",
        education: "शिक्षा",
        community: "समुदाय",
        emergencyContact: "आपातकालीन संपर्क",
        triggerSOS: "SOS अलर्ट भेजें",
        learningHub: "कौशल शिक्षा केंद्र",
        eligibleSchemes: "आपके लिए योजनाएं",
        myShop: "मेरी दुकान",
        addProduct: "नया उत्पाद जोड़ें",
        editProduct: "उत्पाद संपादित करें",
        delete: "हटाएं",
        saveChanges: "परिवर्तन सहेजें",
    },
    Telugu: {
        home: "హోమ్",
        skillHub: "నైపుణ్య కేంద్రం",
        health: "ఆరోగ్యం",
        tagline: "సాంకేతికత ద్వారా గ్రామీణ మహిళల సాధికారత",
        periodBot: "పిరియడ్ కేర్ బాట్",
        pregnancyBot: "ప్రెగ్నెన్సీ కేర్ బాట్",
        askSomething: "ఏదైనా అడగండి...",
        startChat: "చాట్ ప్రారంభించండి",
        listen: "వినండి",
        speak: "మాట్లాడండి",
        sakhiTyping: "సఖి టైప్ చేస్తోంది...",
        periodTrackerSetup: "పిరియడ్ ట్రాకర్ సెటప్",
        yourAge: "మీ వయస్సు",
        lastPeriodDate: "చివరి పిరియడ్ తేదీ",
        registerAsCreator: "క్రియేటర్‌గా నమోదు చేసుకోండి",
        villageMarket: "గ్రామ మార్కెట్",
        buy: "కొనండి",
        price: "ధర",
        name: "పేరు",
        village: "గ్రామం",
        skills: "నైపుణ్యాలు",
        experience: "అనుభవం",
        contact: "సంప్రదింపు",
        submit: "సమర్పించు",
        close: "మూసివేయి",
        login: "లాగిన్",
        signup: "సైన్ అప్",
        phoneNumber: "ఫోన్ నంబర్",
        password: "పాస్వర్డ్",
        noAccount: "ఖాతా లేదా?",
        haveAccount: "ఇప్పటికే ఖాతా ఉందా?",
        welcomeBack: "మళ్ళీ స్వాగతం",
        createAccount: "ఖాతాను సృష్టించండి",
        profile: "ప్రొఫైల్",
        myOrders: "నా ఆర్డర్లు",
        paymentHistory: "చెల్లింపు చరిత్ర",
        chatWithCreator: "సఖి (క్రియేటర్) తో చాట్ చేయండి",
        status: "స్థితి",
        completed: "పూర్తయింది",
        pending: "పెండింగ్‌లో ఉంది",
        amount: "మొత్తం",
        date: "తేదీ",
        messagePlaceholder: "క్రియేటర్‌కి సందేశం పంపండి...",
        chooseAssistant: "మీ సహాయకుడిని ఎంచుకోండి",
        assistantDesc: "మా AI-ఆధారిత సహాయకులు గోప్యత మరియు సంరక్షణతో మీకు మార్గనిర్దేశం చేయడానికి ఇక్కడ ఉన్నారు. (వైద్యుడికి ప్రత్యామ్నాయం కాదు).",
        pregnancyJourney: "ప్రెగ్నెన్సీ ప్రయాణం",
        pregnancyStartDate: "ప్రెగ్నెన్సీ ప్రారంభ తేదీ (సుమారు)",
        safety: "రక్షణ",
        shelterMap: "రక్షణ మ్యాప్",
        sos: "అత్యవసర బటన్ (SOS)",
        schemes: "ప్రభుత్వ పథకాలు",
        education: "విద్య",
        community: "సంఘం",
        emergencyContact: "అత్యవసర సంప్రదింపు",
        triggerSOS: "SOS అలర్ట్ పంపండి",
        learningHub: "నైపుణ్య విద్యా కేంద్రం",
        eligibleSchemes: "మీ కోసం పథకాలు",
        myShop: "నా దుకాణం",
        addProduct: "కొత్త వస్తువును చేర్చు",
        editProduct: "వస్తువును సవరించు",
        delete: "తొలగించు",
        saveChanges: "మార్పులను సేవ్ చేయి",
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const saved = localStorage.getItem('language');
        return (saved && translations[saved]) ? saved : 'English';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const t = translations[language] || translations['English'];

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
